"""added_new_table_opensearch_query

Revision ID: d78eb6efbf3f
Revises: 20b4e7b582f5
Create Date: 2024-07-14 18:02:27.813002+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78eb6efbf3f'
down_revision: Union[str, None] = '20b4e7b582f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isearchui_opensearch_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=True),
    sa.Column('opensearch_query', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isearchui_opensearch_queries_id'), 'isearchui_opensearch_queries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_isearchui_opensearch_queries_id'), table_name='isearchui_opensearch_queries')
    op.drop_table('isearchui_opensearch_queries')
    # ### end Alembic commands ###
