"""increased stack_trace size

Revision ID: 0b4d754e2531
Revises: 3d88ea869e9f
Create Date: 2024-06-14 09:27:04.948272+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b4d754e2531'
down_revision: Union[str, None] = '3d88ea869e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_audit_logs', 'service',
               existing_type=mysql.ENUM('CORE', 'ISEARCHUI', 'JOB', 'EXTRAS'),
               nullable=True)
    op.alter_column('core_audit_logs', 'stack_trace',
               existing_type=mysql.VARCHAR(length=4096),
               type_=sa.String(length=8192),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_audit_logs', 'stack_trace',
               existing_type=sa.String(length=8192),
               type_=mysql.VARCHAR(length=4096),
               existing_nullable=True)
    op.alter_column('core_audit_logs', 'service',
               existing_type=mysql.ENUM('CORE', 'ISEARCHUI', 'JOB', 'EXTRAS'),
               nullable=False)
    # ### end Alembic commands ###
