"""add-unique-key-for-query-name

Revision ID: 26ede02b7b89
Revises: d78eb6efbf3f
Create Date: 2024-07-16 09:25:32.412045+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26ede02b7b89'
down_revision: Union[str, None] = 'd78eb6efbf3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('isearchui_opensearch_queries', 'name',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.create_unique_constraint(None, 'isearchui_opensearch_queries', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'isearchui_opensearch_queries', type_='unique')
    op.alter_column('isearchui_opensearch_queries', 'name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###
