"""added_new_column_to_isearchui_users_table

Revision ID: 20b4e7b582f5
Revises: 670caa4535e6
Create Date: 2024-07-11 20:03:09.201300+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b4e7b582f5'
down_revision: Union[str, None] = '670caa4535e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('isearchui_users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('isearchui_users', 'created_at')
    # ### end Alembic commands ###
