"""added_new_column_to_isearchui_users_table

Revision ID: 670caa4535e6
Revises: 0b4d754e2531
Create Date: 2024-07-11 19:47:05.959237+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670caa4535e6'
down_revision: Union[str, None] = '0b4d754e2531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('isearchui_users', sa.Column('created_by', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('isearchui_users', 'created_by')
    # ### end Alembic commands ###
