"""initial db

Revision ID: 7254605ac600
Revises: 
Create Date: 2024-05-13 11:35:26.634680+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7254605ac600'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_tenants',
    sa.Column('uuid', sa.String(length=36), server_default=sa.text('(UUID())'), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_by', sa.String(length=256), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_admin', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_core_tenants_client_id'), 'core_tenants', ['client_id'], unique=True)
    op.create_index(op.f('ix_core_tenants_uuid'), 'core_tenants', ['uuid'], unique=False)
    op.create_table('isearchui_search_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('impression', sa.Enum('POSITIVE', 'NEGATIVE', 'NONE', name='impressionenum'), nullable=False),
    sa.Column('search_text', sa.String(length=512), nullable=True),
    sa.Column('search_device', sa.String(length=256), nullable=True),
    sa.Column('search_persona', sa.Enum('Operator', 'Engineer', name='personaenum'), nullable=False),
    sa.Column('feedback_text', sa.String(length=512), nullable=True),
    sa.Column('feedback_timestamp', sa.DateTime(), nullable=True),
    sa.Column('feedback_by', sa.String(length=256), nullable=True),
    sa.Column('on_document_id', sa.String(length=512), nullable=True),
    sa.Column('on_document_title', sa.String(length=512), nullable=True),
    sa.Column('on_document_description', sa.String(length=512), nullable=True),
    sa.Column('on_result_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isearchui_search_feedbacks_id'), 'isearchui_search_feedbacks', ['id'], unique=False)
    op.create_table('isearchui_users',
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Guest', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('job_email_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('event_type', sa.Enum('SERVER_ERROR', 'DOCUMENT_ERROR', name='emailsettingseventtype'), nullable=True),
    sa.Column('category', sa.Enum('APPLICATION', 'KAAS', 'DOCHEBO', name='emailsettingscategory'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'event_type', 'category', name='_email_event_category_uc')
    )
    op.create_index(op.f('ix_job_email_subscribers_email'), 'job_email_subscribers', ['email'], unique=False)
    op.create_index(op.f('ix_job_email_subscribers_id'), 'job_email_subscribers', ['id'], unique=False)
    op.create_table('job_saves',
    sa.Column('job_key', sa.String(length=256), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('last_successful_run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_key')
    )
    op.create_index(op.f('ix_job_saves_job_key'), 'job_saves', ['job_key'], unique=False)
    op.create_table('core_audit_logs',
    sa.Column('id', sa.String(length=32), server_default=sa.text('(UUID())'), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=256), nullable=True),
    sa.Column('service', sa.Enum('CORE', 'ISEARCHUI', 'JOB', name='serviceenum'), nullable=True),
    sa.Column('log_level', sa.Enum('INFO', 'ERROR', 'CRITICAL', name='loglevelenum'), nullable=True),
    sa.Column('context', sa.Enum('API', 'SERVICE', name='contextenum'), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('log_input', sa.String(length=1024), nullable=True),
    sa.Column('stack_trace', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_audit_logs_id'), 'core_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_core_audit_logs_tenant_id'), 'core_audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_core_audit_logs_timestamp'), 'core_audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_audit_logs_timestamp'), table_name='core_audit_logs')
    op.drop_index(op.f('ix_core_audit_logs_tenant_id'), table_name='core_audit_logs')
    op.drop_index(op.f('ix_core_audit_logs_id'), table_name='core_audit_logs')
    op.drop_table('core_audit_logs')
    op.drop_index(op.f('ix_job_saves_job_key'), table_name='job_saves')
    op.drop_table('job_saves')
    op.drop_index(op.f('ix_job_email_subscribers_id'), table_name='job_email_subscribers')
    op.drop_index(op.f('ix_job_email_subscribers_email'), table_name='job_email_subscribers')
    op.drop_table('job_email_subscribers')
    op.drop_table('isearchui_users')
    op.drop_index(op.f('ix_isearchui_search_feedbacks_id'), table_name='isearchui_search_feedbacks')
    op.drop_table('isearchui_search_feedbacks')
    op.drop_index(op.f('ix_core_tenants_uuid'), table_name='core_tenants')
    op.drop_index(op.f('ix_core_tenants_client_id'), table_name='core_tenants')
    op.drop_table('core_tenants')
    # ### end Alembic commands ###
