"""initial db

Revision ID: c70d64a43038
Revises: 7254605ac600
Create Date: 2024-05-13 11:38:49.678620+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c70d64a43038'
down_revision: Union[str, None] = '7254605ac600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_audit_logs', 'id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('(uuid())'))
    op.alter_column('core_audit_logs', 'tenant_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_audit_logs', 'tenant_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('core_audit_logs', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text('(uuid())'))
    # ### end Alembic commands ###
