"""migration-name

Revision ID: 097aa9f78cb6
Revises: 18a7d6d48204
Create Date: 2025-03-18 15:37:21.127085+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097aa9f78cb6'
down_revision: Union[str, None] = '18a7d6d48204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragas_evaluation', sa.Column('session_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ragas_evaluation', 'session_id')
    # ### end Alembic commands ###
