"""added new client-indigo

Revision ID: be53fb46f4f4
Revises: 097aa9f78cb6
Create Date: 2025-05-19 15:30:02.476178+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be53fb46f4f4'
down_revision: Union[str, None] = '097aa9f78cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_tenants', 'client_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_tenants', 'client_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
