resources:
  repositories:
    - repository: templates
      type: githubenterprise
      name: codeway/templates
      endpoint: ghe

trigger:
  branches:
    include:
      - release_to_prod
  paths:
    exclude:
      - Devops/Prod/charts
      - Devops/Prod/codeway-release-to-prod-ci.yaml
      - Devops/Prod/codeway-release-to-prod-cd.yaml

variables:
  - group: nextjs-prod-knowledgesearch
  - name: branch
    value: release_to_prod

stages:
  - template: templates/codeway-docker-image-v1-beta2.yaml@templates
    parameters:
      anchoreScan: false
      trivyScan: true
      trivyFailOnIssuesFound: false
      project: knowledge_search
      dockerfile: Dockerfile
      repo: ks_printos_${{ variables.branch }}
      registryType: harbor
      releaseBranch: ${{ variables.branch }}
      registryParameters:
        - registry: harbor-knowledge_search

  - template: templates/codeway-helm-library-v0.yaml@templates
    parameters:
      releaseBranch: ${{ variables.branch }}
      chartName: ks-printos-release-to-prod
      chartDir: $(Build.SourcesDirectory)/Devops/Prod/charts/ks-printos
      versionMajorMinor: '5.8'
      publishRepositories:
        - name: ks-printos-release-to-prod
          url: https://harbor.ext.hp.com/chartrepo/knowledge_search
          username: $(harbor_username)
          password: $(harbor_password)
          type: harbor
