apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ks-printos.labels" . | nindent 4 }}
  namespace: {{ include "ks-printos.namespace" .}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ks-printos.selectorLabels" . | nindent 4 }}
